### ISSUE TITLE
'nojump' raises an exception when used with triclinic systems

### ISSUE THREAD

**Issue by p-j-smith** [p-j-smith/lipyphilic#105]
**Describe the bug**
`lipyphilic.transformations.nojump` can't be used with triclinic systems - it always raises a `ValueError` because the system is triclinic, even if the `lipyphilic.transformations.triclinic_to_orthorhombic` is used first.

**To Reproduce**
``` python
from lipyphilic._simple_systems.simple_systems import TRICLINIC
from lipyphilic.transformations import nojump, triclinic_to_orthorhombic

universe = MDAnalysis.Universe(TRICLINIC)
atoms = universe.atoms
universe.trajectory.add_transformations(
    triclinic_to_orthorhombic(ag=atoms),
    nojump(ag=atoms, nojump_x=True, nojump_y=True, nojump_z=True),
)
```

**Expected behaviour**
No error is raised.

**Actual behaviour**
The following error is raised:
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/paul/git/lipyphilic/src/lipyphilic/transformations.py", line 197, in __init__
    raise ValueError("nojump requires an orthorhombic box. Please use the on-the-fly "
ValueError: nojump requires an orthorhombic box. Please use the on-the-fly transformation :class:`lipyphilic.transformations.triclinic_to_orthorhombic` before calling nojump
```

**Additional context**
- Which version of lipyphilic are you using?
0.10
- Which version of Python are you using?
3.10

**Comment by p-j-smith** [comment]
There are a few issues with this transformation (see also #113), and now that there is an [implementation in MDAnalysis](https://docs.mdanalysis.org/stable/documentation_pages/transformations/nojump.html) I will remove the one in lipyphilic and recommend people to use `MDAnalysis.transformations.NoJump` instead.
