### ISSUE TITLE
[BUG] fails on import,  "No module named 'lipyphilic._lipyferric'"

### ISSUE THREAD

**Issue by recombinatrix** [p-j-smith/lipyphilic#145]
**Describe the bug**

I have installed lipyphilic this morning using conda.  Importing lipyphilic fails with the following error message:

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/uqadaqu1/anaconda3/envs/lipyphilic/lib/python3.10/site-packages/lipyphilic/__init__.py", line 1, in <module>
    from ._lipyferric import __version__
ModuleNotFoundError: No module named 'lipyphilic._lipyferric'
```

When I check the contents of `/home/uqadaqu1/anaconda3/envs/lipyphilic/lib/python3.10/site-packages/lipyphilic/` I can see the following:

```
leaflets/
__pycache__/
lib/
_simple_systems/
analysis/
_lipyferric.cpython-312-x86_64-linux-gnu.so*
transformations/
__init__.py
plotting/
```

**To Reproduce**
Fresh installation

```
$ conda create -n lipyphilic -c conda-forge python=3.10 lipyphilic`

$ conda activate lipyphilic

$ python
Python 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import  lipyphilic as lpp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/uqadaqu1/anaconda3/envs/lipyphilic/lib/python3.10/site-packages/lipyphilic/__init__.py", line 1, in <module>
    from ._lipyferric import __version__
ModuleNotFoundError: No module named 'lipyphilic._lipyferric'
```

**Expected behaviour**
Module imports

**Actual behaviour**
Module fails to import

**Additional context**

This is happening on two machines.  One is running MacOS monterey 12.2.1, and the other is running Ubuntu 20.04.4 LTS (Focal Fossa

Big long text dump of the conda installation

```
## Package Plan ##

  environment location: /home/uqadaqu1/anaconda3/envs/lipyphilic

  added / updated specs:
    - lipyphilic
    - python=3.10


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu
  attrs              conda-forge/noarch::attrs-23.2.0-pyh71513ae_0
  biopython          conda-forge/linux-64::biopython-1.84-py310hc51659f_0
  blosc              conda-forge/linux-64::blosc-1.21.6-hef167b5_0
  brotli             conda-forge/linux-64::brotli-1.1.0-hd590300_1
  brotli-bin         conda-forge/linux-64::brotli-bin-1.1.0-hd590300_1
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h4bc722e_7
  c-ares             conda-forge/linux-64::c-ares-1.32.2-h4bc722e_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2024.7.4-hbcca054_0
  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1
  certifi            conda-forge/noarch::certifi-2024.7.4-pyhd8ed1ab_0
  cftime             conda-forge/linux-64::cftime-1.6.4-py310h261611a_0
  colorama           conda-forge/noarch::colorama-0.4.6-pyhd8ed1ab_0
  contourpy          conda-forge/linux-64::contourpy-1.2.1-py310hd41b1e2_0
  cycler             conda-forge/noarch::cycler-0.12.1-pyhd8ed1ab_0
  fasteners          conda-forge/noarch::fasteners-0.17.3-pyhd8ed1ab_0
  fonttools          conda-forge/linux-64::fonttools-4.53.1-py310h5b4e0ec_0
  freetype           conda-forge/linux-64::freetype-2.12.1-h267a509_2
  freud              conda-forge/linux-64::freud-3.1.0-py310he880d76_1
  griddataformats    conda-forge/noarch::griddataformats-1.0.2-pyhd8ed1ab_0
  gsd                conda-forge/linux-64::gsd-3.3.0-py310h261611a_0
  h5py               conda-forge/linux-64::h5py-3.11.0-nompi_py310hf054cd7_102
  hdf4               conda-forge/linux-64::hdf4-4.2.15-h2a13503_7
  hdf5               conda-forge/linux-64::hdf5-1.14.3-nompi_hdf9ad27_105
  icu                conda-forge/linux-64::icu-75.1-he02047a_0
  joblib             conda-forge/noarch::joblib-1.4.2-pyhd8ed1ab_0
  keyutils           conda-forge/linux-64::keyutils-1.6.1-h166bdaf_0
  kiwisolver         conda-forge/linux-64::kiwisolver-1.4.5-py310hd41b1e2_1
  krb5               conda-forge/linux-64::krb5-1.21.3-h659f571_0
  lcms2              conda-forge/linux-64::lcms2-2.16-hb7c19ff_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.40-hf3520f5_7
  lerc               conda-forge/linux-64::lerc-4.0.0-h27087fc_0
  libaec             conda-forge/linux-64::libaec-1.1.3-h59595ed_0
  libblas            conda-forge/linux-64::libblas-3.9.0-22_linux64_openblas
  libbrotlicommon    conda-forge/linux-64::libbrotlicommon-1.1.0-hd590300_1
  libbrotlidec       conda-forge/linux-64::libbrotlidec-1.1.0-hd590300_1
  libbrotlienc       conda-forge/linux-64::libbrotlienc-1.1.0-hd590300_1
  libcblas           conda-forge/linux-64::libcblas-3.9.0-22_linux64_openblas
  libcurl            conda-forge/linux-64::libcurl-8.8.0-hca28451_1
  libdeflate         conda-forge/linux-64::libdeflate-1.20-hd590300_0
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-64::libev-4.33-hd590300_2
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-14.1.0-h77fa898_0
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-14.1.0-h69a702a_0
  libgfortran5       conda-forge/linux-64::libgfortran5-14.1.0-hc5f4f2c_0
  libgomp            conda-forge/linux-64::libgomp-14.1.0-h77fa898_0
  libhwloc           conda-forge/linux-64::libhwloc-2.11.1-default_hecaa2ac_1000
  libiconv           conda-forge/linux-64::libiconv-1.17-hd590300_2
  libjpeg-turbo      conda-forge/linux-64::libjpeg-turbo-3.0.0-hd590300_1
  liblapack          conda-forge/linux-64::liblapack-3.9.0-22_linux64_openblas
  libnetcdf          conda-forge/linux-64::libnetcdf-4.9.2-nompi_h135f659_114
  libnghttp2         conda-forge/linux-64::libnghttp2-1.58.0-h47da74e_1
  libnsl             conda-forge/linux-64::libnsl-2.0.1-hd590300_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.27-pthreads_hac2b453_1
  libpng             conda-forge/linux-64::libpng-1.6.43-h2797004_0
  libsqlite          conda-forge/linux-64::libsqlite-3.46.0-hde9e2c9_0
  libssh2            conda-forge/linux-64::libssh2-1.11.0-h0841786_0
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-14.1.0-hc0a3c3a_0
  libtiff            conda-forge/linux-64::libtiff-4.6.0-h1dd3fc0_3
  libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0
  libwebp-base       conda-forge/linux-64::libwebp-base-1.4.0-hd590300_0
  libxcb             conda-forge/linux-64::libxcb-1.16-hd590300_0
  libxcrypt          conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1
  libxml2            conda-forge/linux-64::libxml2-2.12.7-he7c6b58_4
  libzip             conda-forge/linux-64::libzip-1.10.1-h2629f0a_3
  libzlib            conda-forge/linux-64::libzlib-1.3.1-h4ab18f5_1
  lipyphilic         conda-forge/noarch::lipyphilic-0.11.0-pyha770c72_0
  lz4-c              conda-forge/linux-64::lz4-c-1.9.4-hcb278e6_0
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.9.1-py310h0b1de36_0
  mda-xdrlib         conda-forge/noarch::mda-xdrlib-0.2.0-pyhd8ed1ab_0
  mdanalysis         conda-forge/linux-64::mdanalysis-2.7.0-py310hcc13569_1
  mmtf-python        conda-forge/noarch::mmtf-python-1.1.3-pyhd8ed1ab_0
  mrcfile            conda-forge/noarch::mrcfile-1.5.1-pyhd8ed1ab_0
  msgpack-python     conda-forge/linux-64::msgpack-python-1.0.8-py310h25c7140_0
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0
  ncurses            conda-forge/linux-64::ncurses-6.5-h59595ed_0
  netcdf4            conda-forge/linux-64::netcdf4-1.7.1-nompi_py310hf3005e6_101
  networkx           conda-forge/noarch::networkx-3.3-pyhd8ed1ab_1
  numpy              conda-forge/linux-64::numpy-1.26.4-py310hb13e2d6_0
  openjpeg           conda-forge/linux-64::openjpeg-2.5.2-h488ebb8_0
  openssl            conda-forge/linux-64::openssl-3.3.1-h4bc722e_2
  packaging          conda-forge/noarch::packaging-24.1-pyhd8ed1ab_0
  pandas             conda-forge/linux-64::pandas-2.2.2-py310hf9f9076_1
  patsy              conda-forge/noarch::patsy-0.5.6-pyhd8ed1ab_0
  pillow             conda-forge/linux-64::pillow-10.4.0-py310hebfe307_0
  pip                conda-forge/noarch::pip-24.0-pyhd8ed1ab_0
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h36c2ea0_1001
  pyedr              conda-forge/noarch::pyedr-0.8.0-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.1.2-pyhd8ed1ab_0
  python             conda-forge/linux-64::python-3.10.14-hd12c33a_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.9.0-pyhd8ed1ab_0
  python-tzdata      conda-forge/noarch::python-tzdata-2024.1-pyhd8ed1ab_0
  python_abi         conda-forge/linux-64::python_abi-3.10-4_cp310
  pytng              conda-forge/linux-64::pytng-0.3.3-py310h6ea5394_0
  pytz               conda-forge/noarch::pytz-2024.1-pyhd8ed1ab_0
  qhull              conda-forge/linux-64::qhull-2020.2-h434a139_5
  readline           conda-forge/linux-64::readline-8.2-h8228510_1
  rowan              conda-forge/noarch::rowan-1.3.0.post1-pyh9f0ad1d_0
  scikit-learn       conda-forge/linux-64::scikit-learn-1.5.1-py310h146d792_0
  scipy              conda-forge/linux-64::scipy-1.14.0-py310h93e2701_1
  seaborn            conda-forge/noarch::seaborn-0.13.2-hd8ed1ab_2
  seaborn-base       conda-forge/noarch::seaborn-base-0.13.2-pyhd8ed1ab_2
  setuptools         conda-forge/noarch::setuptools-70.3.0-pyhd8ed1ab_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  snappy             conda-forge/linux-64::snappy-1.2.1-ha2e4443_0
  statsmodels        conda-forge/linux-64::statsmodels-0.14.2-py310h261611a_0
  tbb                conda-forge/linux-64::tbb-2021.12.0-h434a139_3
  threadpoolctl      conda-forge/noarch::threadpoolctl-3.5.0-pyhc1e730c_0
  tidynamics         conda-forge/noarch::tidynamics-1.1.2-pyhd8ed1ab_0
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_h4845f30_101
  tqdm               conda-forge/noarch::tqdm-4.66.4-pyhd8ed1ab_0
  tzdata             conda-forge/noarch::tzdata-2024a-h0c530f3_0
  unicodedata2       conda-forge/linux-64::unicodedata2-15.1.0-py310h2372a71_0
  wheel              conda-forge/noarch::wheel-0.43.0-pyhd8ed1ab_1
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.11-hd590300_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h7f98852_0
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0
  zlib               conda-forge/linux-64::zlib-1.3.1-h4ab18f5_1
  zstd               conda-forge/linux-64::zstd-1.5.6-ha6fb4c9_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate lipyphilic
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Retrieving notices: ...working... done
```

**Comment by ErikPoppleton** [comment]
I am having the same problem.  It appears to be a specific problem with the 0.11.0 version, because I am able to do `conda install conda-forge::lipyphilic==0.10.0` and then am able to install without a problem.

**Comment by p-j-smith** [comment]
Sorry for the slow response and the installation issues. Seems like it's a problem with the conda forge package not picking up the Rust extension I added in 0.11. As a temporary workaround you could use pip to install lipyphilic (`pip install lipyphilic`) - I've just tested it and this installs correctly. I'll try to take a look at the conda packaging soon

**Comment by RubenChM** [comment]
There is only [one conda package](https://anaconda.org/conda-forge/lipyphilic/files) built with `_lipyferric.cpython-312-x86_64-linux-gnu.so*`, meaning if you are using other architecture that is not linux with python=3.12, this import will fail.
I create a [pull request](https://github.com/conda-forge/lipyphilic-feedstock/pull/14) to help fixing fix this problem.

**Comment by p-j-smith** [comment]
This should be fixed now thanks to @RubenChM's efforts, thanks @RubenChM!
